# названия устройства
esphome:
  name: $name
  friendly_name: $friendly_name
#названия устойства
esp32:
  board: esp32dev
  framework:
    type: arduino

# ////////////////////////////////////////
# ///// начало не изменяемая часть ///////
# ////////////////////////////////////////
# Включить ведение журнала
logger:
# Включить API Home Assistant (нужно для подтверждения подключения)
api:
  encryption:
    key: !secret API #
#пароль для обновления по воздуху
ota:
  password: !secret OTA #
# подключения к домашней wifi сети
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Включить резервную точку доступа (портал авторизации) на случай сбоя подключения к Wi-Fi.
  ap:
    ssid: ${name}
    password: !secret AP
#
captive_portal:
# веб морда
web_server:
# //////////////////////////
# конец не изменяемой части
# //////////////////////////
# начало изменяемой части
# //////////////////////////

# переменные 
#substitutions: # спользования $devicename или ${devicename}
  name: esp32-01-kuxn
  friendly_name: esp32-01-kuxn

# резерв или образ на github, изменяя его на сайте прилетает обновления 
dashboard_import:
  package_import_url: github://zad1ak/esphome/esp32-02-ble.yaml

# //////////////////////////
# конец изменяемой части
# //////////////////////////

button:
  - platform: restart # перезагрузка узла
    name: "Перезагрузка"
    entity_category: config

esp32_ble_tracker:
  scan_parameters:

    active: false


binary_sensor:

# Mi Smart 7 pro
  - platform: ble_presence
    mac_address: D0:62:2C:80:A9:A5
    name: "Mi Smart 7 pro"

  - platform: ble_presence
    mac_address: E0:CC:F8:F2:BE:ED
    name: "Xaomi Redmi Note 9 Pro"
sensor:
  - platform: xiaomi_lywsd03mmc
    mac_address: "A4:C1:38:AF:A5:58"
    bindkey: "c80ebc2095b91b369dba9b374d27c7f3"
    temperature:
      name: "LYWSD03MMC Temperature"
    humidity:
      name: "LYWSD03MMC Humidity"
    battery_level:
      name: "LYWSD03MMC Battery Level"
 

#  - platform: xiaomi_lywsd02
#    mac_address: e7:2e:00:f1:4c:95
#    temperature:
#      name: "Xiaomi Clock Temperature"
#    humidity:
#      name: "Xiaomi Clock Humidity"
      
#
